### ISSUE TITLE
Allow selection of empty feature list

### ISSUE THREAD

**Issue by Longarithm** [utka/nayduck#4]
It's currently impossible to select only tests with empty feature list on the page with test results:

Example: http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1626

We can put `--features nightly_protocol --features nightly_protocol_features` to the "Features" text field to look over tests with corresponding features. But empty field doesn't filter anything, so to look over tests without enabled features we have to scroll everything down.

Suggestion: make "Features" a dropdown selection over all values.

**Comment by utka** [comment]
I set it up, that  space (" ") going to filter by empty feature  set

**Comment by Longarithm** [comment]
It works, thank you!
